- type: job
  id: TfaHighCommandIntern
  name: job-name-tfa-high-command-intern
  description: job-description-tfa-high-command-intern
  playTimeTracker: JobTfaHighCommandIntern
  adminWhitelist: true # only admin-rank holders see or take it
  overrideConsoleVisibility: false # keeps it off the ID console's job presets, which otherwise follow setPreference
  startingGear: TfaHighCommandInternGear
  alwaysUseSpawner: true
  icon: "JobIconNanotrasen" # Idk it looks good enough
  supervisors: job-supervisors-tfa-highcomm-officials
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - TdfChiefEnforcer
  - TdfLieutenant
  - TdfPatrolTeamLeader
  ranks:
    RankHighCommandIntern: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TDF # not TDF, but friendly and works with them
    - type: CryoSleepRadioOverride
      overrides:
      - CentCom # com radio
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Triadian # Highcomm status, so they would 100% know this, atleast somewhat
    languagesUnderstood:
    - Triadian
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: TfaHighCommandInternGear
  equipment: # clothing comes from the JobTfaHighCommandIntern loadout
    id: TfaHighComInternPda
    ears: ClothingHeadsetHighCommand
    pocket1: BoxFolderBlack
    pocket2: LuxuryPen
