- type: job
  id: TfaHighCommandRep
  name: job-name-tfa-high-command
  description: job-description-tfa-high-command
  playTimeTracker: JobTfaHighCommandRep
  adminWhitelist: true # only admin-rank holders see or take it
  overrideConsoleVisibility: false # keeps it off the ID console's job presets, which otherwise follow setPreference
  startingGear: TfaHighCommandRepGear
  alwaysUseSpawner: true
  icon: "JobIconNanotrasen" # Idk it looks good enough
  supervisors: job-supervisors-tfa-director
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - TdfChiefEnforcer
  - TdfLieutenant
  - TdfPatrolTeamLeader
  ranks:
    RankHighCommandRepresentative: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TDF # not TDF, but friendly and works with them
    - type: CryoSleepRadioOverride
      overrides:
      - CentCom # com radio
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Triadian # Official status, so they would 100% know this, atleast somewhat
    languagesUnderstood:
    - Triadian
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: TfaHighCommandRepGear
  equipment: # clothing comes from the JobTfaHighCommandRep loadout
    id: TfaHighComPda
    ears: ClothingHeadsetAltHighCommand
    belt: WeaponEnergyRevolver
    pocket1: BoxFolderBlack
    pocket2: LuxuryPen
