using System.Linq;
using Content.Shared._DV.Traits;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitCategory : BoxContainer
{
    public event Action<ProtoId<TraitPrototype>, bool>? OnTraitToggled;

    private readonly TraitCategoryPrototype _category;
    private readonly List<TraitPrototype> _allTraits;
    private readonly Dictionary<ProtoId<TraitPrototype>, TraitEntry> _traitEntries = new();

    private bool _isExpanded;

    public int SelectedCount;
    public int PointsSpent;

    /// <summary>
    /// Triad: extra slots granted to this category by selected granter traits (e.g. Foreigner), set by
    /// the parent tab so the "X / N" label reflects the effective cap, not just the base MaxTraits.
    /// </summary>
    public int BonusSlots;

    public TraitCategory(TraitCategoryPrototype category, List<TraitPrototype> traits)
    {
        RobustXamlLoader.Load(this);

        _category = category;
        _allTraits = traits;
        _isExpanded = category.DefaultExpanded;

        CategoryNameLabel.Text = Loc.GetString(category.Name);
        SetAccentColor(category.AccentColor);

        HeaderButton.OnPressed += _ => ToggleExpanded();

        PopulateTraits();
        UpdateExpandedState();
        UpdateStats();
    }

    private void SetAccentColor(Color color)
    {
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = color }; // dumb stylesheet modulation workaround
    }

    private void PopulateTraits()
    {
        TraitsContainer.RemoveAllChildren();
        _traitEntries.Clear();

        foreach (var trait in _allTraits)
        {
            var entry = new TraitEntry(trait);
            // Triad: hide the per-trait cost in categories with no point budget; the cost is noise there.
            entry.SetCostVisible(_category.HasPointLimit);
            entry.OnToggled += selected => OnTraitEntryToggled(trait.ID, selected);
            _traitEntries[trait.ID] = entry;
            TraitsContainer.AddChild(entry);
        }
    }

    private void OnTraitEntryToggled(ProtoId<TraitPrototype> traitId, bool selected)
    {
        OnTraitToggled?.Invoke(traitId, selected);
    }

    private void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        ContentPanel.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }

    public void UpdateStats()
    {
        SelectedCount = _traitEntries.Values.Count(e => e.IsSelected);
        PointsSpent = _traitEntries.Values
            .Where(e => e.IsSelected)
            .Sum(e => e.TraitCost);

        if (_category.HasTraitLimit)
        {
            // Triad: show the effective cap (base + granted slots), so Foreigner's extra language slots read correctly.
            CategoryStatsLabel.Text = Loc.GetString("trait-category-traits",
                ("selected", SelectedCount),
                ("max", _category.MaxTraits!.Value + BonusSlots));
        }
        else
        {
            CategoryStatsLabel.Text = Loc.GetString("trait-category-traits-unlimited",
                ("selected", SelectedCount));
        }

        if (_category.HasPointLimit)
        {
            CategoryPointsLabel.Visible = true;
            // Triad: show points still AVAILABLE (max - spent), so negative-cost traits raise the
            // number instead of showing a confusing "-4 / 6". Matches the global points label.
            CategoryPointsLabel.Text = Loc.GetString("trait-category-points",
                ("available", _category.MaxPoints!.Value - PointsSpent),
                ("max", _category.MaxPoints!.Value));
        }
        else
        {
            CategoryPointsLabel.Visible = false;
        }
    }

    public void SetTraitSelected(ProtoId<TraitPrototype> traitId, bool selected)
    {
        if (_traitEntries.TryGetValue(traitId, out var entry))
        {
            entry.SetSelected(selected);
        }
    }

    /// <summary>
    /// Triad: the traits in this category, so the parent tab can compute per-trait affordability.
    /// </summary>
    public IReadOnlyList<TraitPrototype> Traits => _allTraits;

    /// <summary>
    /// Triad: push the computed budget state for one trait down to its entry (drives the grey "can't afford" look).
    /// </summary>
    public void SetTraitAffordable(ProtoId<TraitPrototype> traitId, bool affordable, string? reason = null)
    {
        if (_traitEntries.TryGetValue(traitId, out var entry))
            entry.SetAffordable(affordable, reason);
    }

    public void ClearSelection()
    {
        foreach (var (_, entry) in _traitEntries)
        {
            entry.SetSelected(false);
        }

        SelectedCount = 0;
        PointsSpent = 0;
        UpdateStats();
    }

    /// <summary>
    /// Gets the IDs of all currently selected traits in this category.
    /// </summary>
    public IEnumerable<ProtoId<TraitPrototype>> GetSelectedTraitIds()
    {
        return _traitEntries
            .Where(kvp => kvp.Value.IsSelected)
            .Select(kvp => kvp.Key);
    }

    /// <summary>
    /// Filters traits based on search text only
    /// </summary>
    public void FilterTraits(string searchText)
    {
        var searching = !string.IsNullOrEmpty(searchText);
        var hasVisibleTraits = false;

        foreach (var (traitId, entry) in _traitEntries)
        {
            var trait = _allTraits.First(t => t.ID == traitId);
            var name = Loc.GetString(trait.Name);
            var description = Loc.GetString(trait.Description);

            var matchesSearch = !searching ||
                                name.Contains(searchText, StringComparison.OrdinalIgnoreCase) ||
                                description.Contains(searchText, StringComparison.OrdinalIgnoreCase);

            entry.Visible = matchesSearch;

            if (entry.Visible)
                hasVisibleTraits = true;
        }

        // Hide entire category if no traits match search
        Visible = hasVisibleTraits;

        // Triad: categories default to collapsed, so an active search has to force the matching ones open or the
        // results would be hidden inside the collapsed panel. Clearing the search restores the expanded/collapsed
        // state the user (or the default) left it in.
        if (searching)
        {
            ContentPanel.Visible = hasVisibleTraits;
            ExpandIcon.Text = hasVisibleTraits ? "▼" : "▶";
        }
        else
        {
            UpdateExpandedState();
        }
    }

    /// <summary>
    /// Updates condition states for all trait entries based on current job/species.
    /// Traits that don't meet conditions are disabled but still visible.
    /// </summary>
    public void UpdateConditions(ProtoId<JobPrototype>? jobId, ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences, IReadOnlySet<ProtoId<TraitPrototype>>? traits, string? companyName)  // Mono - Company condition
    {
        foreach (var (_, entry) in _traitEntries)
        {
            entry.UpdateConditionsMet(jobId, speciesId, antagPreferences, traits, companyName); // Mono - Company condition
        }

        // Update stats since some traits may have been deselected
        UpdateStats();
    }

    /// <summary>
    /// Checks if a trait in this category meets its conditions.
    /// </summary>
    public bool TraitMeetsConditions(ProtoId<TraitPrototype> traitId)
    {
        return _traitEntries.TryGetValue(traitId, out var entry) && entry.MeetsConditions;
    }
}
