using System.Linq;
using Content.Client.Stylesheets; // Mono - Backport of Sheetlet to stylesheet
using Content.Shared._DV.CCVars;
using Content.Shared._DV.Traits;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitsTab : BoxContainer
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IStylesheetManager _stylesheet = default!; // Mono - Backport of Sheetlet to stylesheet

    /// <summary>
    /// Event fired when trait selection changes.
    /// </summary>
    public event Action<HashSet<ProtoId<TraitPrototype>>>? OnTraitsChanged;

    private readonly Dictionary<ProtoId<TraitCategoryPrototype>, TraitCategory> _categoryUis = new();
    private readonly HashSet<ProtoId<TraitPrototype>> _selectedTraits = new();

    private int _maxGlobalTraits;
    private int _maxGlobalPoints;
    private int _currentTraitCount;
    private int _currentPointsSpent;

    private string _currentSearchText = string.Empty;
    private bool _awaitingLayoutUpdate;

    private HumanoidCharacterProfile? _profile;

    public TraitsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Stylesheet = _stylesheet.SheetTraits; // Mono - Backport of Sheetlet to stylesheet

        SearchBar.OnTextChanged += OnSearchTextChanged;
        _prototype.PrototypesReloaded += OnProtoReload;

        // Subscribe to CVars
        _cfg.OnValueChanged(DCCVars.MaxTraitCount, OnMaxTraitCountChanged, true);
        _cfg.OnValueChanged(DCCVars.MaxTraitPoints, OnMaxTraitPointsChanged, true);

        PopulateCategories();
        UpdateGlobalStats();
    }

    private void OnMaxTraitCountChanged(int value)
    {
        _maxGlobalTraits = value;
        UpdateGlobalStats();
    }

    private void OnMaxTraitPointsChanged(int value)
    {
        _maxGlobalPoints = value;
        UpdateGlobalStats();
    }

    private void OnProtoReload(PrototypesReloadedEventArgs args)
    {
        // Don't refresh if control has been disposed
        if (Disposed)
            return;

        if (args.WasModified<TraitPrototype>() || args.WasModified<TraitCategoryPrototype>())
            RefreshTraits();
    }

    public void RefreshTraits()
    {
        PopulateCategories();
        UpdateGlobalStats();
    }

    private void PopulateCategories()
    {
        CategoriesContainer.RemoveAllChildren();
        _categoryUis.Clear();

        var categories = _prototype.EnumeratePrototypes<TraitCategoryPrototype>()
            .OrderBy(c => c.Priority)
            .ThenBy(c => Loc.GetString(c.Name))
            .ToList();

        // Triad: order by cost ascending so the biggest point GAIN (most negative) sits at the top and the
        // biggest point COST (most positive) at the bottom; ties (and all-zero categories like Accents) fall
        // back to alphabetical by name.
        var traitsByCategory = _prototype.EnumeratePrototypes<TraitPrototype>()
            .GroupBy(t => t.Category)
            .ToDictionary(g => g.Key, g => g.OrderBy(t => t.Cost).ThenBy(t => Loc.GetString(t.Name)).ToList());

        foreach (var category in categories)
        {
            if (!traitsByCategory.TryGetValue(category.ID, out var traits) || traits.Count == 0)
                continue;

            var categoryUi = new TraitCategory(category, traits);
            categoryUi.OnTraitToggled += OnTraitToggled;
            _categoryUis[category.ID] = categoryUi;
            CategoriesContainer.AddChild(categoryUi);
        }

        // Apply current filters and conditions
        ApplySearchFilter();
        UpdateAllConditions();
        UpdateAffordability();
    }

    private void OnTraitToggled(ProtoId<TraitPrototype> traitId, bool selected)
    {
        var trait = _prototype.Index(traitId);

        if (selected)
        {
            // Check global limits. Triad: _maxGlobalTraits <= 0 means unlimited.
            if (_maxGlobalTraits > 0 && _currentTraitCount >= _maxGlobalTraits)
            {
                RevertTraitToggle(traitId);
                return;
            }

            // Triad: _maxGlobalPoints <= 0 means unlimited, so the global points gate drops out and only
            // per-category MaxPoints constrains spending (mirrors the unlimited-count gate above).
            if (_maxGlobalPoints > 0 && _currentPointsSpent + trait.Cost > _maxGlobalPoints)
            {
                RevertTraitToggle(traitId);
                return;
            }

            // Check category limits
            if (_categoryUis.TryGetValue(trait.Category, out var categoryUi))
            {
                var categoryProto = _prototype.Index(trait.Category);
                // Triad: granter traits (GrantsCategorySlots) raise the effective cap; mirror the server calc.
                if (categoryProto.HasTraitLimit &&
                    categoryUi.SelectedCount >= categoryProto.MaxTraits!.Value + GetGrantedSlots(trait.Category))
                {
                    RevertTraitToggle(traitId);
                    return;
                }

                if (categoryProto.HasPointLimit &&
                    categoryUi.PointsSpent + trait.Cost > categoryProto.MaxPoints!.Value)
                {
                    RevertTraitToggle(traitId);
                    return;
                }

                // Check if trait meets conditions
                if (!categoryUi.TraitMeetsConditions(traitId))
                {
                    RevertTraitToggle(traitId);
                    return;
                }
            }

            _selectedTraits.Add(traitId);
            _currentTraitCount++;
            _currentPointsSpent += trait.Cost;
        }
        else
        {
            _selectedTraits.Remove(traitId);
            _currentTraitCount--;
            _currentPointsSpent -= trait.Cost;
        }

        UpdateGlobalStats();
        UpdateCategoryStats(trait.Category);
        UpdateAllConditions();
        UpdateAffordability();
        OnTraitsChanged?.Invoke(_selectedTraits);
    }

    // Triad: grey out unselected traits the player can no longer afford (global points, category slots, or
    // category points), mirroring the gates in OnTraitToggled. Selected traits stay affordable so they remain
    // clickable to deselect. Rule-blocked entries are handled separately (red) and ignore this.
    private void UpdateAffordability()
    {
        foreach (var (categoryId, categoryUi) in _categoryUis)
        {
            var categoryProto = _prototype.Index(categoryId);
            var grantedSlots = GetGrantedSlots(categoryId);

            foreach (var trait in categoryUi.Traits)
            {
                // Selected entries always remain clickable (so you can deselect to free budget).
                if (_selectedTraits.Contains(trait.ID))
                {
                    categoryUi.SetTraitAffordable(trait.ID, true);
                    continue;
                }

                // Determine affordability and, if blocked, the specific reason to show on hover. Order mirrors
                // the OnTraitToggled gates; the first limit hit wins the explanation.
                var affordable = true;
                string? reason = null;

                if (_maxGlobalPoints > 0 && _currentPointsSpent + trait.Cost > _maxGlobalPoints)
                {
                    affordable = false;
                    reason = Loc.GetString("disabled-traits-reason-points-limit");
                }
                else if (categoryProto.HasTraitLimit &&
                    categoryUi.SelectedCount >= categoryProto.MaxTraits!.Value + grantedSlots)
                {
                    affordable = false;
                    reason = Loc.GetString("disabled-traits-reason-category-limit", ("category", Loc.GetString(categoryProto.Name)));
                }
                else if (categoryProto.HasPointLimit &&
                    categoryUi.PointsSpent + trait.Cost > categoryProto.MaxPoints!.Value)
                {
                    affordable = false;
                    reason = Loc.GetString("disabled-traits-reason-category-points", ("category", Loc.GetString(categoryProto.Name)));
                }

                categoryUi.SetTraitAffordable(trait.ID, affordable, reason);
            }
        }
    }

    // Triad: sum extra slots granted to a category by currently-selected granter traits (e.g. Foreigner).
    private int GetGrantedSlots(ProtoId<TraitCategoryPrototype> category)
    {
        var total = 0;
        foreach (var selectedId in _selectedTraits)
        {
            if (_prototype.Index(selectedId).GrantsCategorySlots.TryGetValue(category, out var slots))
                total += slots;
        }
        return total;
    }

    private void RevertTraitToggle(ProtoId<TraitPrototype> traitId)
    {
        var trait = _prototype.Index(traitId);
        if (_categoryUis.TryGetValue(trait.Category, out var categoryUi))
        {
            categoryUi.SetTraitSelected(traitId, _selectedTraits.Contains(traitId));
        }
    }

    // Triad: the footer line reflects the ACTUAL limit configuration so it stays honest if a server sets global
    // caps (max_count/max_points > 0) or per-category caps. Hidden entirely when nothing is limited.
    private void UpdateFooterInfo()
    {
        var globalLimited = _maxGlobalTraits > 0 || _maxGlobalPoints > 0;
        var categoryLimited = false;
        foreach (var cat in _prototype.EnumeratePrototypes<TraitCategoryPrototype>())
        {
            if (cat.HasTraitLimit || cat.HasPointLimit)
            {
                categoryLimited = true;
                break;
            }
        }

        string? key =
            globalLimited && categoryLimited ? "trait-editor-footer-info-both" :
            globalLimited ? "trait-editor-footer-info-global" :
            categoryLimited ? "trait-editor-footer-info-category" :
            null;

        FooterInfoLabel.Visible = key != null;
        if (key != null)
            FooterInfoLabel.Text = Loc.GetString(key);
    }

    private void UpdateGlobalStats()
    {
        UpdateFooterInfo();
        // Triad: _maxGlobalTraits <= 0 means unlimited, so drop the now-meaningless "X / N" counter.
        GlobalTraitCountLabel.Visible = _maxGlobalTraits > 0;
        if (_maxGlobalTraits > 0)
            GlobalTraitCountLabel.Text = $"{_currentTraitCount} / {_maxGlobalTraits}";

        // Triad: _maxGlobalPoints <= 0 means unlimited, so hide the whole global points label + bar and let
        // per-category point dials speak for themselves. Bail before the bar math, which divides by the max.
        PointsProgressContainer.Visible = _maxGlobalPoints > 0;
        if (_maxGlobalPoints <= 0)
            return;

        // Calculate remaining points (clamped to not go below 0 in display)
        var remainingPoints = _maxGlobalPoints - _currentPointsSpent;
        GlobalPointsLabel.Text = $"{remainingPoints} / {_maxGlobalPoints}";

        // Calculate progress bar percentage - clamp between 0 and 1
        var percentage = Math.Clamp((float)remainingPoints / _maxGlobalPoints, 0f, 1f);

        // Update progress bar using percentage-based sizing
        var parent = GlobalPointsBar.Parent;
        if (parent != null)
        {
            var parentWidth = parent.Width;
            // If parent width is 0 (not laid out yet), defer until layout happens
            if (parentWidth > 0)
            {
                GlobalPointsBar.SetWidth = (int)((parentWidth - 2) * percentage);
                _awaitingLayoutUpdate = false;
            }
            else if (!_awaitingLayoutUpdate)
            {
                // Schedule update after parent layout (only once)
                _awaitingLayoutUpdate = true;
                parent.OnResized += OnProgressBarParentResized;
            }
        }

        // Update progress bar color class
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarFull");
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarPartial");
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarLow");
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarEmpty");

        GlobalPointsBar.AddStyleClass(percentage switch
        {
            >= 0.99f => "TraitsProgressBarFull",
            >= 0.5f => "TraitsProgressBarPartial",
            > 0f => "TraitsProgressBarLow",
            _ => "TraitsProgressBarEmpty"
        });
    }

    private void OnProgressBarParentResized()
    {
        _awaitingLayoutUpdate = false;
        UpdateGlobalStats();
    }

    private void UpdateCategoryStats(ProtoId<TraitCategoryPrototype> categoryId)
    {
        if (_categoryUis.TryGetValue(categoryId, out var categoryUi))
        {
            // Triad: feed the granted-slot total so the category's "X / N" cap reflects granters (e.g. Foreigner).
            categoryUi.BonusSlots = GetGrantedSlots(categoryId);
            categoryUi.UpdateStats();
        }
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _currentSearchText = args.Text.Trim();
        ApplySearchFilter();
    }

    private void ApplySearchFilter()
    {
        foreach (var (_, categoryUi) in _categoryUis)
        {
            categoryUi.FilterTraits(_currentSearchText);
        }
    }

    /// <summary>
    /// Updates all trait conditions based on current job and species.
    /// Call this when job or species changes in the character creator.
    /// </summary>
    /// <param name="profile">Current profile</param>
    public void UpdateConditions(HumanoidCharacterProfile profile)
    {
        _profile = profile;
        UpdateAllConditions();
    }

    private void UpdateAllConditions()
    {
        foreach (var (_, categoryUi) in _categoryUis)
        {
            // If some fork wants to use the top selected job as well, just add that to the UpdateConditions method in the editor
            categoryUi.UpdateConditions(null, _profile?.Species, _profile?.AntagPreferences, _selectedTraits, _profile?.Company); // Mono - Company condition
        }

        RecalculateStats();
    }

    private void RecalculateStats()
    {
        _currentTraitCount = 0;
        _currentPointsSpent = 0;

        // Rebuild selected traits based on what's actually selected in the UI
        var previouslySelected = new HashSet<ProtoId<TraitPrototype>>(_selectedTraits);
        _selectedTraits.Clear();

        foreach (var (_, categoryUi) in _categoryUis)
        {
            // Get the selected traits from this category
            var selectedInCategory = categoryUi.GetSelectedTraitIds();

            foreach (var traitId in selectedInCategory)
            {
                if (!_prototype.TryIndex(traitId, out var trait))
                    continue;

                _selectedTraits.Add(traitId);
                _currentTraitCount++;
                _currentPointsSpent += trait.Cost;
            }
        }

        UpdateGlobalStats();
        foreach (var (categoryId, _) in _categoryUis)
        {
            UpdateCategoryStats(categoryId);
        }

        UpdateAffordability();

        // Fire event if selection changed
        if (!_selectedTraits.SetEquals(previouslySelected))
        {
            OnTraitsChanged?.Invoke(_selectedTraits);
        }
    }

    /// <summary>
    /// Sets the currently selected traits (e.g., when loading a profile).
    /// </summary>
    public void SetSelectedTraits(IEnumerable<ProtoId<TraitPrototype>> traits)
    {
        // Clear current selection
        foreach (var (_, categoryUi) in _categoryUis)
        {
            categoryUi.ClearSelection();
        }

        _selectedTraits.Clear();
        _currentTraitCount = 0;
        _currentPointsSpent = 0;

        // Apply new selection
        foreach (var traitId in traits)
        {
            if (!_prototype.TryIndex(traitId, out var trait))
                continue;

            _selectedTraits.Add(traitId);
            _currentTraitCount++;
            _currentPointsSpent += trait.Cost;

            if (_categoryUis.TryGetValue(trait.Category, out var categoryUi))
            {
                categoryUi.SetTraitSelected(traitId, true);
            }
        }

        UpdateGlobalStats();
        foreach (var (categoryId, _) in _categoryUis)
        {
            UpdateCategoryStats(categoryId);
        }

        UpdateAffordability();
    }
}
