using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._WF.SafetyDepositBox.BUI;
using Content.Shared._WF.SafetyDepositBox.Components;
using Content.Shared._WF.SafetyDepositBox.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Content.Shared._Triad.CCVar;
using Robust.Shared.Configuration;

// Triad : Refactor Safety Deposit UI to clickable sprite grid with right-side inspect detail (name/desc/price/sprite), buy-after-inspect flow and bank balance.
namespace Content.Client._WF.SafetyDepositBox;

[GenerateTypedNameReferences]
public sealed partial class SafetyDepositConsoleWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    public event Action<string>? OnPurchasePressed;
    public event Action? OnDepositPressed;
    public event Action<Guid>? OnWithdrawPressed;
    public event Action<Guid>? OnReclaimPressed;
    public event Action<Guid>? OnRemovePressed;

    private readonly ButtonGroup _boxButtonGroup = new();
    private readonly Dictionary<string, Button> _boxButtons = new();
    private string? _selectedProtoId;
    private BoxTypeInfo? _selectedBox;
    private int _cachedBankBalance;
    private SafetyDepositConsoleState? _lastState;

    public SafetyDepositConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DepositButton.OnPressed += _ => OnDepositPressed?.Invoke();
        BuyButton.OnPressed += _ =>
        {
            if (_selectedProtoId != null)
                OnPurchasePressed?.Invoke(_selectedProtoId);
        };

        // Start with nothing selected; detail view will show placeholder
        UpdateDetailPanel(null);
    }

    public void UpdateState(SafetyDepositConsoleState state)
    {
        _lastState = state;
        _cachedBankBalance = state.BankBalance;

        RebuildAvailableBoxesGrid(state.AvailableBoxTypes);

        // Update detail panel for current selection (or auto-select first if none)
        if (_selectedProtoId == null && state.AvailableBoxTypes.Count > 0)
        {
            // Auto-select first box (cheapest) for initial UX; keep visuals consistent
            SelectBox(state.AvailableBoxTypes[0].ProtoId, state.AvailableBoxTypes[0]);
        }
        else if (_selectedProtoId != null)
        {
            var selected = state.AvailableBoxTypes.FirstOrDefault(b => b.ProtoId == _selectedProtoId);
            if (selected.ProtoId != null)
            {
                // Refresh panel with latest costs/desc (bank balance may have changed)
                _selectedBox = selected;
                UpdateDetailPanel(selected);
                // Ensure button remains pressed
                if (_boxButtons.TryGetValue(selected.ProtoId, out var btn))
                    btn.Pressed = true;
            }
            else
            {
                // Previously selected proto no longer available
                _selectedProtoId = null;
                _selectedBox = null;
                UpdateDetailPanel(null);
            }
        }
        else
        {
            UpdateDetailPanel(null);
        }

        // Update deposit button
        DepositButton.Disabled = !state.HasBoxInSlot || state.BoxInSlot == null;

        // Update box slot status
        if (state.HasBoxInSlot && state.BoxInSlot != null)
        {
            BoxSlotLabel.Text = Loc.GetString("safety-deposit-console-box-in-slot",
                ("id", state.BoxInSlot.Value.BoxId.ToString()[..8]));
        }
        else
        {
            BoxSlotLabel.Text = Loc.GetString("safety-deposit-console-no-box-in-slot");
        }

        // Update owned boxes list (unchanged logic)
        OwnedBoxesContainer.RemoveAllChildren();

        if (state.OwnedBoxes.Count == 0)
        {
            var noBoxesLabel = new Label
            {
                Text = Loc.GetString("safety-deposit-console-no-boxes"),
                StyleClasses = { "LabelSecondaryColor" },
                HorizontalAlignment = Control.HAlignment.Center,
                Margin = new Thickness(0, 20)
            };
            OwnedBoxesContainer.AddChild(noBoxesLabel);
        }
        else
        {
            var sortedBoxes = state.OwnedBoxes.OrderByDescending(b => b.BoxId).ToList();
            var index = 0;
            foreach (var box in sortedBoxes)
            {
                // Triad (remove black AngleRect background, use Contraband style dark panel #1B1B1E with subtle alternating)
                var rowPanel = new PanelContainer
                {
                    HorizontalExpand = true,
                };
                rowPanel.PanelOverride = new Robust.Client.Graphics.StyleBoxFlat
                {
                    BackgroundColor = index % 2 == 0 ? Color.FromHex("#1B1B1E") : Color.FromHex("#212121")
                };

                var rowContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(8, 4)
                };

                var boxInfoText = !string.IsNullOrEmpty(box.Nickname)
                    ? $"{box.Nickname}"
                    : $"Box {box.BoxId.ToString()[..8]}";

                var boxIdLabel = new Label
                {
                    Text = boxInfoText,
                    HorizontalExpand = true,
                    VerticalAlignment = Control.VAlignment.Center
                };

                string statusText;
                Color statusColor;

                if (box.IsDeposited)
                {
                    statusText = Loc.GetString("safety-deposit-console-box-deposited");
                    statusColor = Color.LightGreen;
                }
                else if (box.LastWithdrawnRoundId.HasValue && box.LastWithdrawnRoundId.Value != state.CurrentRoundId)
                {
                    statusText = Loc.GetString("safety-deposit-console-box-lost");
                    statusColor = Color.Red;
                }
                else
                {
                    statusText = Loc.GetString("safety-deposit-console-box-in-world");
                    statusColor = Color.Yellow;
                }

                var statusLabel = new Label
                {
                    Text = statusText,
                    MinWidth = 80,
                    Align = Label.AlignMode.Right,
                    Margin = new Thickness(0, 0, 5, 0),
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center,
                    FontColorOverride = statusColor
                };

                var isLost = box.LastWithdrawnRoundId.HasValue &&
                             box.LastWithdrawnRoundId.Value != state.CurrentRoundId &&
                             !box.IsDeposited;

                // Triad changes :
                // Box can be removed if deposited (in database) OR lost (missing)
                // Box cannot be removed if "in world" (withdrawn in current round, not deposited)
                var canRemove = box.IsDeposited || isLost;
                var actionButton = new Button
                {
                    Text = isLost
                        ? Loc.GetString("safety-deposit-console-reclaim-button")
                        : Loc.GetString("safety-deposit-console-withdraw-button"),
                    Disabled = !box.IsDeposited && !isLost,
                    MinWidth = 100,
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center
                };

                // Triad : Remove button (shown when box can be removed)
                var removeButton = new ConfirmButton
                {
                    Text = Loc.GetString("safety-deposit-console-remove-button"),
                    ConfirmationText = Loc.GetString("safety-deposit-console-remove-confirmation"),
                    Disabled = !canRemove,
                    MinWidth = 80,
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center,
                    StyleClasses = { "ButtonDanger" }
                };

                var boxId = box.BoxId;
                if (isLost)
                {
                    actionButton.OnPressed += _ => OnReclaimPressed?.Invoke(boxId);
                }
                else
                {
                    actionButton.OnPressed += _ => OnWithdrawPressed?.Invoke(boxId);
                }

                removeButton.OnPressed += _ => OnRemovePressed?.Invoke(boxId);

                rowContainer.AddChild(boxIdLabel);
                rowContainer.AddChild(statusLabel);
                rowContainer.AddChild(actionButton);
                if (canRemove)
                    rowContainer.AddChild(removeButton);
                rowPanel.AddChild(rowContainer);
                OwnedBoxesContainer.AddChild(rowPanel);

                index++;
            }
        }
    }

    private void RebuildAvailableBoxesGrid(List<BoxTypeInfo> boxTypes)
    {
        AvailableBoxesGrid.RemoveAllChildren();
        _boxButtons.Clear();

        foreach (var boxType in boxTypes)
        {
            var button = new Button
            {
                ToggleMode = true,
                Group = _boxButtonGroup,
                StyleClasses = { "OpenBoth" },
                MinSize = new Vector2(140, 140),
                HorizontalExpand = true,
            };

            // Inner layout: sprite on top, label below (only sprite + small text, no price per spec)
            var inner = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new Thickness(6)
            };

            // Triad (style grid items like ContrabandPermit sprite view: bordered dark panel, no white/black backgrounds)
            var viewContainer = new PanelContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                Margin = new Thickness(0, 0, 0, 4)
            };
            viewContainer.PanelOverride = new Robust.Client.Graphics.StyleBoxFlat
            {
                BorderThickness = new Thickness(2),
                BorderColor = Color.FromHex("#ffd688"),
                BackgroundColor = Color.FromHex("#1B1B1E")
            };

            var view = new EntityPrototypeView
            {
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                Scale = new Vector2(2.5f, 2.5f),
                Stretch = SpriteView.StretchMode.Fit,
                MinSize = new Vector2(80, 80),
                Margin = new Thickness(6),
                SetSize = new Vector2(80, 80),
            };

            if (_prototypeManager.TryIndex<EntityPrototype>(boxType.ProtoId, out var proto))
                view.SetPrototype(proto);

            viewContainer.AddChild(view);

            inner.AddChild(viewContainer);
            button.AddChild(inner);

            var protoId = boxType.ProtoId;
            var capturedBox = boxType;
            button.OnPressed += _ => SelectBox(protoId, capturedBox);

            // Preserve selection visual
            if (protoId == _selectedProtoId)
                button.Pressed = true;

            AvailableBoxesGrid.AddChild(button);
            _boxButtons[protoId] = button;
        }
    }

    private void SelectBox(string protoId, BoxTypeInfo boxType)
    {
        _selectedProtoId = protoId;
        _selectedBox = boxType;

        // Update button pressed states (ButtonGroup handles it, but ensure)
        if (_boxButtons.TryGetValue(protoId, out var btn))
            btn.Pressed = true;

        UpdateDetailPanel(boxType);
    }

    private void UpdateDetailPanel(BoxTypeInfo? box)
    {
        var maxBoxes = _cfg.GetCVar(TriadCCVars.SafetyBoxLimit);
        var ownedBoxesCount = _lastState?.OwnedBoxes.Count ?? 0;
        var atMaxBoxes = ownedBoxesCount >= maxBoxes;

        if (box == null)
        {
            SelectedBoxNameLabel.SetMessage(Loc.GetString("safety-deposit-console-select-a-box"));
            SelectedBoxDescriptionLabel.SetMessage(Loc.GetString("safety-deposit-console-select-to-view"));
            SelectedBoxPriceLabel.Text = "-";

            BankBalanceLabel.Text = BankSystemExtensions.ToSpesoString(_cachedBankBalance);
            BalanceAfterLabel.Text = "-";
            BalanceAfterLabel.FontColorOverride = Color.White;
            BuyButton.Disabled = true;
            BuyButton.Text = Loc.GetString("safety-deposit-console-buy-button");
            return;
        }

        var b = box.Value;
        SelectedBoxNameLabel.SetMessage(b.Name);
        SelectedBoxDescriptionLabel.SetMessage(string.IsNullOrWhiteSpace(b.Description)
            ? Loc.GetString("safety-deposit-console-no-description")
            : b.Description);
        SelectedBoxPriceLabel.Text = BankSystemExtensions.ToSpesoString(b.Cost);

        BankBalanceLabel.Text = BankSystemExtensions.ToSpesoString(_cachedBankBalance);
        var after = _cachedBankBalance - b.Cost;
        BalanceAfterLabel.Text = BankSystemExtensions.ToSpesoString(after);

        if (after < 0 || atMaxBoxes)
        {
            if (!atMaxBoxes)
            {
                BalanceAfterLabel.FontColorOverride = Color.Red;
                BuyButton.Text = Loc.GetString("safety-deposit-console-insufficient-funds");
            }
            else
            {
                BuyButton.Text = Loc.GetString("safety-deposit-console-buy-button-limit");
            }
            BuyButton.Disabled = true;
        }
        else
        {
            BalanceAfterLabel.FontColorOverride = Color.LightGreen;
            BuyButton.Disabled = false;
            // Update buy button text to include price for clarity
            BuyButton.Text = Loc.GetString("safety-deposit-console-buy-button-with-price", ("cost", BankSystemExtensions.ToSpesoString(b.Cost)));
        }

        // Fallback if loc missing format string issues: keeps english fallback below
        if (BuyButton.Text.Contains("cost"))
            BuyButton.Text = $"Buy for {BankSystemExtensions.ToSpesoString(b.Cost)}";
    }
}
